FROM node:22-alpine AS base

# Install deps only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install deps based on preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  elif [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  else echo 'Lockfile not found.' && exit 1; \
  fi

# ---------------------------------------------------
# DEV
# ---------------------------------------------------
FROM base as dev

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json
COPY . .

EXPOSE 3000

CMD \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm dev; \
  elif [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  else echo 'Cannot start web app. Exiting now.' && exit 1; \
  fi